[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "crypto"
crate-type = ["staticlib"]

[dependencies]
starknet-crypto = "0.1"
anyhow = "1.0"