name: Release ReddioCrypto.xcframework
on:
  workflow_dispatch: {}
  push:
    tags:
    - reddio-swift/**

jobs:
  publish:
    runs-on: macos-13
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Rust toolchain aarch64-apple-darwin
      uses: actions-rs/toolchain@v1
      with:
        target: aarch64-apple-darwin
    - name: Setup Rust toolchain aarch64-apple-ios
      uses: actions-rs/toolchain@v1
      with:
        target: aarch64-apple-ios
    - name: Setup Rust toolchain x86_64-apple-ios
      uses: actions-rs/toolchain@v1
      with:
        target: x86_64-apple-ios
    - name: Build ReddioCrypto.xcframework
      run: |
          cd reddio-swift && make
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ReddioCrypto.xcframework
        path: |
          output/ReddioCrypto.xcframework
