name: Build Unity Plugin Zip
on: 
  workflow_dispatch: {}
  label:
    types:
      - created
jobs:
  linux_shared_library:
    name: Linux Shared Library
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust toolchain x86_64-unknown-linux-gnu
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-unknown-linux-gnu
      - name: Compile
        run: |
          cd crypto && cargo build --release --target x86_64-unknown-linux-gnu
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libcrypto-x86_64-unknown-linux-gnu
          path: |
            crypto/target/x86_64-unknown-linux-gnu/release/libcrypto.a
            crypto/target/x86_64-unknown-linux-gnu/release/libcrypto.so
  android_share_library:
    name: Android Shared Library
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup cargo-ndk
        run: |
          cargo install cargo-ndk
      - name: Setup Rust toolchain aarch64-linux-android
        uses: actions-rs/toolchain@v1
        with:
          target: aarch64-linux-android
      - name: Setup Rust toolchain armv7-linux-androideabi
        uses: actions-rs/toolchain@v1
        with:
          target: armv7-linux-androideabi
      - name: Setup Rust toolchain x86_64-linux-android
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-linux-android
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25
      - name: Build Android Shared Library
        run: |
          cd crypto && cargo ndk -t armeabi-v7a -t arm64-v8a -t x86_64 build --release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libcrypto-aarch64-linux-android
          path: |
            crypto/target/aarch64-linux-android/release/libcrypto.a
            crypto/target/aarch64-linux-android/release/libcrypto.so
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libcrypto-armv7-linux-androideabi
          path: |
            crypto/target/armv7-linux-androideabi/release/libcrypto.a
            crypto/target/armv7-linux-androideabi/release/libcrypto.so
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libcrypto-x86_64-linux-android
          path: |
            crypto/target/x86_64-linux-android/release/libcrypto.a
            crypto/target/x86_64-linux-android/release/libcrypto.so
  windows_shared_library:
    name: Windows Shared Library
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust toolchain x86_64-pc-windows-msvc
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-pc-windows-msvc
      - name: Compile
        run: |
          cd crypto && cargo build --release --target x86_64-pc-windows-msvc
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libcrypto-x86_64-pc-windows-msvc
          path: |
            crypto/target/x86_64-pc-windows-msvc/release/crypto.lib
            crypto/target/x86_64-pc-windows-msvc/release/crypto.dll
  macos_shared_library:
    name: macOS Shared Library
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Rust toolchain aarch64-apple-darwin
        uses: actions-rs/toolchain@v1
        with:
          target: aarch64-apple-darwin
      - name: Setup Rust toolchain x86_64-apple-darwin
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-apple-darwin
      - name: Build macOS shared Library
        run: |
          cd crypto && cargo build --target x86_64-apple-darwin --target aarch64-apple-darwin --release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libcrypto-aarch64-apple-darwin
          path: |
            crypto/target/aarch64-apple-darwin/release/libcrypto.a
            crypto/target/aarch64-apple-darwin/release/libcrypto.dylib
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libcrypto-x86_64-apple-darwin
          path: |
            crypto/target/x86_64-apple-darwin/release/libcrypto.a
            crypto/target/x86_64-apple-darwin/release/libcrypto.dylib
  ios_static_library:
    name: iOS Static Library
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup cargo-lipo
        run: |
          cargo install cargo-lipo
      - name: Setup Rust toolchain aarch64-apple-ios
        uses: actions-rs/toolchain@v1
        with:
          target: aarch64-apple-ios
      - name: Setup Rust toolchain x86_64-apple-ios
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-apple-ios
      - name: Build iOS Static Library
        run: |
          cd crypto && cargo lipo --release
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libcrypto-universal-apple-ios
          path: |
            crypto/target/universal/release/libcrypto.a
  unity_plugin_zip:
    name: Package Unity Plugin Zip
    runs-on: ubuntu-20.04
    needs:
      - linux_shared_library
      - android_share_library
      - windows_shared_library
      - macos_shared_library
      - ios_static_library
    steps:
      - name: Prepare Playground
        run: mkdir -p artifacts
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: artifacts
      - name: Restructure Libraries
        run: |
          mkdir -p unity/Plugins/Android/arm64
          mkdir -p unity/Plugins/Android/armeabi-v7a
          mkdir -p unity/Plugins/Android/x86_64
          mkdir -p unity/Plugins/iOS
          mkdir -p unity/Plugins/Editor/x86_64
          mkdir -p unity/Plugins/Editor/aarch64

          # iOS
          cp artifacts/libcrypto-universal-apple-ios/libcrypto.a unity/Plugins/iOS/libcrypto-universal-apple-ios.a

          # Android
          cp artifacts/libcrypto-aarch64-linux-android/libcrypto.so unity/Plugins/Android/arm64/libcrypto-aarch64-linux-android.so
          cp artifacts/libcrypto-armv7-linux-androideabi/libcrypto.so unity/Plugins/Android/armeabi-v7a/libcrypto-armv7-linux-androideabi.so
          cp artifacts/libcrypto-x86_64-linux-android/libcrypto.so unity/Plugins/Android/x86_64/libcrypto-x86_64-linux-android.so

          # Editor / Standalone
          cp artifacts/libcrypto-x86_64-apple-darwin/libcrypto.dylib unity/Plugins/Editor/x86_64/libcrypto-x86_64-apple-darwin.dylib
          cp artifacts/libcrypto-aarch64-apple-darwin/libcrypto.dylib unity/Plugins/Editor/aarch64/libcrypto-aarch64-apple-darwin.dylib
          cp artifacts/libcrypto-x86_64-pc-windows-msvc/crypto.dll unity/Plugins/Editor/x86_64/libcrypto-x86_64-pc-windows-msvc.dll
          cp artifacts/libcrypto-x86_64-unknown-linux-gnu/libcrypto.so unity/Plugins/Editor/x86_64/libcrypto-x86_64-unknown-linux-gnu.so
      - name: Build the Zip
        uses: thedoctor0/zip-release@main
        with:
          type: zip
          filename: reddio-sdk-unity-plugin.zip
          directory: unity
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: unity/reddio-sdk-unity-plugin.zip
